export const Config = {
    PAYLOAD_FORMAT_INDICATOR : '00',
    MERCHANT_ACCOUNT :'26',
    MERCHANT_ACCOUNT_GUI : '00',
    MERCHANT_ACCOUNT_KEY : '01',
    MERCHANT_ACCOUNT_DESCRIPTION : '02',
    MERCHANT_CATEGORY_CODE : '52',
    TRANSACTION_CURRENCY : '53',
    TRANSACTION_AMOUNT : '54',
    COUNTRY_CODE : '58',
    MERCHANT_NAME : '59',
    MERCHANT_CITY : '60',
    ADDITIONAL_DATA_FIELD_TEMPLATE : '62',
    ADDITIONAL_DATA_FIELD_TEMPLATE_TXID : '05',
    CRC16 : '63',
    MERCHANT_GUI_URL : 'br.gov.bcb.pix'
}